Revert "Simplify test workflow to continue on test failure"
This reverts commit 3ac4cbf3ab2fc2492ffd37420fba2cc77ef17e16.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -42,8 +42,9 @@ jobs:
         cp .env.example .env
 
     - name: Run tests
-      run: pytest --cov=./
-      continue-on-error: true
+      run: |
+        pytest --cov=./ || exit_code=$?
+        echo "exit_code=$exit_code" >> $GITHUB_ENV
 
     - name: Upload Coverage Report as Artifact
       uses: actions/upload-artifact@v4
@@ -58,5 +59,13 @@ jobs:
       if: always()
 
     - name: Fail if tests failed
-      if: failure()
-      run: exit 1
+      run: |
+        if [ -n "$exit_code" ] && [ "$exit_code" -ne 0 ]; then
+          echo "Tests failed with exit code $exit_code."
+          exit $exit_code
+        else
+          echo "Tests passed successfully."
+        fi
+      shell: bash
+      env:
+        exit_code: ${{ env.exit_code }}
